[package]
name = "feroxbuster"
version = "1.0.0"
authors = ["epi <epibar052@gmail.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3"}
tokio = {version = "0.2", features = ["full"] }
log = "0.4"
env_logger = "0.7"
reqwest = "0.10"
clap = "~2.27.0"
lazy_static = "1.4"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 'z'  # optimize for size
lto = true
codegen-units = 1
panic = 'abort'
